
interface ExpProps {
}
export default function Experience ({  }: ExpProps) {

  return (
    <section id='experience' className='text-dark dark:text-light flex flex-col justify-center items-center w-full '>

      <h2 className='text-xl w-5/6 my-4 border-b border-b-dark dark:border-b-light'>Experience</h2>
    
      {
        [
          {title: 'AI Trainer', company: 'DataAnnotation', url: 'https://www.dataannotation.tech/', date: 'March 2024 - Present', description: 'Code review and critique multiple languages including Python, Java, JS, C/C++, Rust. Response editing and writing with careful attention to detail and correctness, proper grammar and vocabulary, and overall helpfulness. '},
          {title: 'Security Analyst', company: 'A2Secure', url: 'https://www.a2secure.com/en/', date: 'May 2022 - May 2024', description: 'Perform detailed analyses regarding security incidents generated by various cloud infrastructures (predominantly Azure and MS Defender, Elastic SIEM, SentinelOne, Datadog, Crowdstrike, GCP); verify and log incident or escalate to L2 as necessary. Analyze and respond to reports involving phishing and quarantined emails; block senders, domains, and URLs as necessary in order to mitigate threat impact.'},
          {title: 'Lab Consultant', company: 'Pitt IT', url: 'https://www.technology.pitt.edu/', date: 'June 2022 - October 2022', description: 'Resolved technology dilemmas for peer students in the computer labs, including computer, printer, and website services. Monitored and maintained network of printers on University of Pittsburgh\'s campus, ensuring minimal downtime and maximum quality'},
        ].map( (item, ind) => (
          <div key={ind} className='w-3/4 mx-auto text-justify border border-solid border-dark dark:border-light p-2 '>
            <span className='w-full flex flex-row justify-between items-center '>
              <h1 className='font-semibold text-2xl mt-2 '>{ item.title }</h1>
              <time className='font-light text-lg '>{ item.date }</time>
            </span>
            
            <a className='font-light text-lg ' href={item.url} target='_blank' rel='noopener noreferrer'>{ item.company }</a><br/>
            <p>{ item.description }</p>
          </div>
        ))
      }
      

    </section>
  )
}